stages:
  - build
  - deploy

variables:
  deploy_host: 10.10.144.25

stg_build:
  stage: build
  image: golang:1.16.15
  script:
    - echo "Build stage has started"
    - go build
  artifacts:
    paths:
      - ./pig
      - resources/

stg_deploy:
  stage: deploy
  image: alpine:latest
  when: on_success
  needs:
    - job: stg_build
      artifacts: true
  before_script:
    - if [ -z ${CI_PROJ_RSA} ]; then echo "CI_PROJ_RSA not set" ; exit 1 ; fi
    - apk add ansible openssh
    - mkdir -p ~/.ssh
    - echo "${CI_PROJ_RSA}" | tr -d '\r' > ~/.ssh/id_rsa
    - ssh-keyscan -t ecdsa,ed25519 -H ${deploy_host} >> ~/.ssh/known_hosts 2>&1    
    - chmod -R 400 ~/.ssh
  script:
    - echo "Deploy stage has started"
    - mkdir -p /etc/ansible
    - echo -e "[managed]\n${deploy_host}" > /etc/ansible/hosts
    - ansible-playbook -u student ./deploy.yml
