apiVersion: v1
kind: Service
metadata:
  name: k8s-pig-app
spec:
  selector:
    app: k8s-pig-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  type: NodePort
