apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres.conf: |
    include_if_exists = 'master.conf'
    include_if_exists = 'replica.conf'
  master.conf: |
    wal_level = hot_standby
    max_wal_senders = 5
    wal_keep_segments = 32
  replica.conf: |
    hot_standby = on
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    replication     replication     all
